type User @table {
  email: String!
  displayName: String!
  userType: String!
  createdAt: Timestamp!
  passwordHash: String
  phoneNumber: String
  address: String
}

type Vendor @table {
  user: User!
  name: String!
  contactEmail: String!
  createdAt: Timestamp!
  description: String
  logoUrl: String
  physicalStoreLocation: String
  openingHours: String
}

type Product @table {
  vendor: Vendor!
  name: String!
  price: Float!
  stockQuantity: Int!
  createdAt: Timestamp!
  description: String
  imageUrl: String
  category: String
}

type Order @table {
  customer: User!
  orderDate: Timestamp!
  totalAmount: Float!
  status: String!
  createdAt: Timestamp!
  shippingAddress: String
  paymentMethod: String
}

type OrderItem @table {
  order: Order!
  product: Product!
  quantity: Int!
  unitPrice: Float!
  subtotal: Float
}